// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // java 侧边栏
  Java面经: [
    {
      type: 'category',
      label: '面试技巧',
      items: [
        { type: 'autogenerated', dirName: '01-Java/01-面试技巧' },
      ],
    },
    {
      type: 'category',
      label: '基础知识',
      items: [
        { type: 'autogenerated', dirName: '01-Java/02-基础知识' },
      ],
    },
    {
      type: 'category',
      label: '集合',
      items: [
        { type: 'autogenerated', dirName: '01-Java/03-集合' },
      ],
    },
    {
      type: 'category',
      label: 'IO相关',
      items: [
        { type: 'autogenerated', dirName: '01-Java/04-IO相关' },
      ],
    },
    {
      type: 'category',
      label: 'JVM',
      items: [
        { type: 'autogenerated', dirName: '01-Java/05-JVM' },
      ],
    },
    {
      type: 'category',
      label: '类加载',
      items: [
        { type: 'autogenerated', dirName: '01-Java/06-类加载' },
      ],
    },
    {
      type: 'category',
      label: '并发多线程',
      items: [
        { type: 'autogenerated', dirName: '01-Java/07-并发多线程' },
      ],
    },
    {
      type: 'category',
      label: 'Spring',
      items: [
        { type: 'autogenerated', dirName: '01-Java/08-Spring' },
      ],
    },
  ],
};

export default sidebars;
