// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {

  // java 侧边栏
  Java相关: [
    {
      type: 'category',
      label: '面试技巧',
      items: [
        { type: 'autogenerated', dirName: '01-Java/01-面试技巧' },
      ],
    },
    {
      type: 'category',
      label: '基础知识',
      items: [
        { type: 'autogenerated', dirName: '01-Java/02-基础知识' },
      ],
    },
    {
      type: 'category',
      label: '集合',
      items: [
        { type: 'autogenerated', dirName: '01-Java/03-集合' },
      ],
    },
    {
      type: 'category',
      label: 'IO相关',
      items: [
        { type: 'autogenerated', dirName: '01-Java/04-IO相关' },
      ],
    },
    {
      type: 'category',
      label: 'JVM',
      items: [
        { type: 'autogenerated', dirName: '01-Java/05-JVM' },
      ],
    },
    {
      type: 'category',
      label: '类加载',
      items: [
        { type: 'autogenerated', dirName: '01-Java/06-类加载' },
      ],
    },
    {
      type: 'category',
      label: '并发多线程',
      items: [
        { type: 'autogenerated', dirName: '01-Java/07-并发多线程' },
      ],
    },
    {
      type: 'category',
      label: '设计模式',
      items: [
        { type: 'autogenerated', dirName: '01-Java/10-设计模式' },
      ],
    },
    {
      type: 'category',
      label: 'Stream流相关',
      items: [
        { type: 'autogenerated', dirName: '01-Java/16-Stream流相关' },
      ],
    },
    {
      type: 'category',
      label: '恶意攻击',
      items: [
        { type: 'autogenerated', dirName: '01-Java/20-恶意攻击' },
      ],
    },
  ],
  // 开发工具 侧边栏
  开发工具: [
    {
      type: 'category',
      label: 'Maven',
      items: [
        { type: 'autogenerated', dirName: '05-开发工具/01-Maven' },
      ],
    },
    {
      type: 'category',
      label: 'Git',
      items: [
        { type: 'autogenerated', dirName: '05-开发工具/02-Git' },
      ],
    },
    {
      type: 'category',
      label: 'Docker',
      items: [
        { type: 'autogenerated', dirName: '05-开发工具/03-Docker' },
      ],
    },
    {
      type: 'category',
      label: '日志',
      items: [
        { type: 'autogenerated', dirName: '05-开发工具/04-日志' },
      ],
    },
  ],
  // 基础内功 侧边栏
  基础内功: [
    {
      type: 'category',
      label: '操作系统',
      items: [
        { type: 'autogenerated', dirName: '06-基础内功/01-操作系统' },
      ],
    },
    {
      type: 'category',
      label: '网络',
      items: [
        { type: 'autogenerated', dirName: '06-基础内功/02-网络' },
      ],
    },
    {
      type: 'category',
      label: '数据结构',
      items: [
        { type: 'autogenerated', dirName: '06-基础内功/03-数据结构' },
      ],
    },
  ],
  // 数据库 侧边栏
  数据库: [
    {
      type: 'category',
      label: 'MySQL',
      items: [
        { type: 'autogenerated', dirName: '11-数据库/01-MySQL' },
      ],
    },
    {
      type: 'category',
      label: 'Redis',
      items: [
        { type: 'autogenerated', dirName: '11-数据库/02-Redis' },
      ],
    },
    {
      type: 'category',
      label: 'Oracle',
      items: [
        { type: 'autogenerated', dirName: '11-数据库/03-Oracle' },
      ],
    },
  ],
  // 框架中间件 侧边栏
  框架中间件: [
    {
      type: 'category',
      label: 'Spring',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/08-Spring' },
      ],
    },
    {
      type: 'category',
      label: 'Mybatis',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/09-Mybatis' },
      ],
    },
    {
      type: 'category',
      label: 'SpringCloud',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/21-SpringCloud' },
      ],
    },
    {
      type: 'category',
      label: 'Zookeeper',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/22-Zookeeper' },
      ],
    },
    {
      type: 'category',
      label: 'Kafka',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/23-Kafka' },
      ],
    },
    {
      type: 'category',
      label: 'RocketMQ',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/24-RocketMQ' },
      ],
    },
    {
      type: 'category',
      label: 'RabbitMQ',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/25-RabbitMQ' },
      ],
    },
    {
      type: 'category',
      label: 'Elasticsearch',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/26-Elasticsearch' },
      ],
    },
    {
      type: 'category',
      label: 'Dubbo',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/27-Dubbo' },
      ],
    },
    {
      type: 'category',
      label: 'Netty',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/28-Netty' },
      ],
    },
    {
      type: 'category',
      label: 'XXL-JOB',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/29-XXL-JOB' },
      ],
    },
    {
      type: 'category',
      label: 'Tomcat',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/30-Tomcat' },
      ],
    },
  ],
  // 进阶设计与性能优化 侧边栏
  进阶设计与性能优化: [
    {
      type: 'category',
      label: '微服务相关',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/01-微服务相关' },
      ],
    },
    {
      type: 'category',
      label: '分布式相关理论',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/02-分布式相关理论' },
      ],
    },
    {
      type: 'category',
      label: '分布式id',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/03-分布式id' },
      ],
    },
    {
      type: 'category',
      label: '限流与熔断',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/04-限流与熔断' },
      ],
    },
    {
      type: 'category',
      label: '缓存的设计',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/05-缓存的设计' },
      ],
    },
    {
      type: 'category',
      label: '布隆过滤器',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/06-布隆过滤器' },
      ],
    },
    {
      type: 'category',
      label: '延迟队列',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/07-延迟队列' },
      ],
    },
    {
      type: 'category',
      label: '问题故障解决',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/10-问题故障解决' },
      ],
    },
    {
      type: 'category',
      label: '分库分表',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/17-分库分表' },
      ],
    },
    {
      type: 'category',
      label: '分布式事务',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/18-分布式事务' },
      ],
    },
    {
      type: 'category',
      label: 'Seata',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/19-Seata' },
      ],
    },
    {
      type: 'category',
      label: 'DDD',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/20-DDD' },
      ],
    },
    {
      type: 'category',
      label: 'AI',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/25-AI' },
      ],
    },
    {
      type: 'category',
      label: '方案设计',
      items: [
        { type: 'autogenerated', dirName: '21-进阶设计与性能优化/30-方案设计' },
      ],
    },
  ],

  // 黑马点评升级版侧边栏
  hmdpPlusSidebar: [
    {
      type: 'category',
      label: '项目特点介绍',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/01-项目特点介绍' },
      ],
    },
    {
      type: 'category',
      label: '项目启动讲解',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/02-项目启动讲解' },
      ],
    },
    {
      type: 'category',
      label: '项目基础讲解',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/03-项目基础讲解' },
      ],
    },
    {
      type: 'category',
      label: '普通版本讲解',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/04-普通版本讲解' },
      ],
    },
    {
      type: 'category',
      label: '分库分表的设计',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/05-分库分表的设计' },
      ],
    },
    {
      type: 'category',
      label: '高并发下的缓存体系设计与风险防护',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/06-高并发下的缓存体系设计与风险防护' },
      ],
    },
    {
      type: 'category',
      label: '高并发下的优惠券抢购实现与优化',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/07-高并发下的优惠券抢购实现与优化' },
      ],
    },
    {
      type: 'category',
      label: '秒杀的护城河：动态令牌与防刷体系',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/08-秒杀的护城河：动态令牌与防刷体系' },
      ],
    },
    {
      type: 'category',
      label: '到券提醒系统设计与最佳实践',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/09-到券提醒系统设计与最佳实践' },
      ],
    },
    {
      type: 'category',
      label: '券务运维与一致性保障',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/10-券务运维与一致性保障' },
      ],
    },
    {
      type: 'category',
      label: '帮你面试通过总结篇',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/11-帮你面试通过总结篇' },
      ],
    },
    {
      type: 'category',
      label: '架构组件讲解',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/12-架构组件讲解' },
      ],
    },
    {
      type: 'category',
      label: '技术精华',
      items: [
        { type: 'autogenerated', dirName: '50-黑马点评升级版/13-技术精华' },
      ],
    },
  ],

  // 大麦 (高并发实战) 侧边栏
  daMaiSidebar: [
    {
      type: 'category',
      label: '项目概要介绍',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/01-项目概要介绍' },
      ],
    },
    {
      type: 'category',
      label: '项目启动讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/02-项目启动讲解' },
      ],
    },
    {
      type: 'category',
      label: '大麦pro介绍',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/03-大麦pro介绍' },
      ],
    },
    {
      type: 'category',
      label: '大麦pro分库分表的增强',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/04-大麦pro分库分表的增强' },
      ],
    },
    {
      type: 'category',
      label: '知识点讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/05-知识点讲解' },
      ],
    },
    {
      type: 'category',
      label: '项目基础讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/06-项目基础讲解' },
      ],
    },
    {
      type: 'category',
      label: '详细业务讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/07-详细业务讲解' },
      ],
    },
    {
      type: 'category',
      label: '分库分表讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/08-分库分表讲解' },
      ],
    },
    {
      type: 'category',
      label: '架构配置讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/09-架构配置讲解' },
      ],
    },
    {
      type: 'category',
      label: '架构组件讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/10-架构组件讲解' },
      ],
    },
    {
      type: 'category',
      label: '技术精华讲解',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/11-技术精华讲解' },
      ],
    },
    {
      type: 'category',
      label: '深挖细节亮点轻松俘获面试官',
      items: [
        { type: 'autogenerated', dirName: '51-大麦/12-深挖细节亮点轻松俘获面试官' },
      ],
    },
  ],

  // 大麦AI (AI实战项目) 侧边栏
  daMaiAiSidebar: [
    {
      type: 'category',
      label: '项目概要介绍',
      items: [
        { type: 'autogenerated', dirName: '52-大麦AI/01-项目概要介绍' },
      ],
    },
    {
      type: 'category',
      label: '项目启动讲解',
      items: [
        { type: 'autogenerated', dirName: '52-大麦AI/02-项目启动讲解' },
      ],
    },
    {
      type: 'category',
      label: 'AI技术介绍',
      items: [
        { type: 'autogenerated', dirName: '52-大麦AI/03-AI技术介绍' },
      ],
    },
    {
      type: 'category',
      label: '第一个对话功能讲解',
      items: [
        { type: 'autogenerated', dirName: '52-大麦AI/04-第一个对话功能讲解' },
      ],
    },
    {
      type: 'category',
      label: '贴心助手功能',
      items: [
        { type: 'autogenerated', dirName: '52-大麦AI/05-贴心助手功能' },
      ],
    },
    {
      type: 'category',
      label: '规则助手功能',
      items: [
        { type: 'autogenerated', dirName: '52-大麦AI/06-规则助手功能' },
      ],
    },
    {
      type: 'category',
      label: '会话列表更新',
      items: [
        { type: 'autogenerated', dirName: '52-大麦AI/07-会话列表更新' },
      ],
    },
  ],

  // link-flow (流量切换系统) 侧边栏
  linkFlowSidebar: [
    {
      type: 'category',
      label: '项目业务介绍',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/01-项目业务介绍' },
      ],
    },
    {
      type: 'category',
      label: '项目功能讲解',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/02-项目功能讲解' },
      ],
    },
    {
      type: 'category',
      label: '项目设计详解',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/03-项目设计详解' },
      ],
    },
    {
      type: 'category',
      label: '微服务负载均衡的增强',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/04-微服务负载均衡的增强' },
      ],
    },
    {
      type: 'category',
      label: '微服务权重功能的增强',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/05-微服务权重功能的增强' },
      ],
    },
    {
      type: 'category',
      label: '关于线程中不为所知的细节',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/06-关于线程中不为所知的细节' },
      ],
    },
    {
      type: 'category',
      label: '技术精华讲解',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/07-技术精华讲解' },
      ],
    },
    {
      type: 'category',
      label: 'Spring-Cloud-Loadblancer源码分析',
      items: [
        { type: 'autogenerated', dirName: '53-流量切换/08-Spring-Cloud-Loadblancer源码分析' },
      ],
    },
  ],
  // dock-data-center (数据中台系统) 侧边栏
  dockDataCenterSidebar: [
    {
      type: 'category',
      label: '项目业务介绍',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/01-项目业务介绍' },
      ],
    },
    {
      type: 'category',
      label: '项目设计基石',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/02-项目设计基石' },
      ],
    },
    {
      type: 'category',
      label: '项目基础讲解',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/03-项目基础讲解' },
      ],
    },
    {
      type: 'category',
      label: '业务的设计',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/04-业务的设计' },
      ],
    },
    {
      type: 'category',
      label: '基础维度的任务执行',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/05-基础维度的任务执行' },
      ],
    },
    {
      type: 'category',
      label: '高级维度的任务执行',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/06-高级维度的任务执行' },
      ],
    },
    {
      type: 'category',
      label: '动态数据源',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/07-动态数据源' },
      ],
    },
    {
      type: 'category',
      label: '指标数据的实时监测',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/08-指标数据的实时监测' },
      ],
    },
    {
      type: 'category',
      label: '消息记录的重要特征',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/09-消息记录的重要特征' },
      ],
    },
    {
      type: 'category',
      label: '技术精华',
      items: [
        { type: 'autogenerated', dirName: '54-数据中台/10-技术精华' },
      ],
    },
  ],

  // 如何学习 侧边栏
  howToStudySidebar: [
    {
      type: 'category',
      label: '学习介绍',
      items: [
        { type: 'autogenerated', dirName: '55-如何学习/01-学习介绍' },
      ],
    },
    {
      type: 'category',
      label: '作者本人',
      items: [
        { type: 'autogenerated', dirName: '55-如何学习/02-作者本人' },
      ],
    },
    {
      type: 'category',
      label: '如何成长',
      items: [
        { type: 'autogenerated', dirName: '55-如何学习/03-如何成长' },
      ],
    },
    {
      type: 'category',
      label: '项目如何贡献',
      items: [
        { type: 'autogenerated', dirName: '55-如何学习/04-项目如何贡献' },
      ],
    },
  ],
};

export default sidebars;