// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 开发工具 侧边栏
  开发工具相关: [
    {
      type: 'category',
      label: 'Maven',
      items: [
        { type: 'autogenerated', dirName: '01-开发工具/01-Maven' },
      ],
    },
    {
      type: 'category',
      label: 'Git',
      items: [
        { type: 'autogenerated', dirName: '01-开发工具/02-Git' },
      ],
    },
    {
      type: 'category',
      label: 'Docker',
      items: [
        { type: 'autogenerated', dirName: '01-开发工具/03-Docker' },
      ],
    },
    {
      type: 'category',
      label: '日志',
      items: [
        { type: 'autogenerated', dirName: '01-开发工具/04-日志' },
      ],
    },
  ],
  // 系统基础内功 侧边栏
  系统基础内功: [
    {
      type: 'category',
      label: '操作系统',
      items: [
        { type: 'autogenerated', dirName: '02-系统基础内功/01-操作系统' },
      ],
    },
    {
      type: 'category',
      label: '网络',
      items: [
        { type: 'autogenerated', dirName: '02-系统基础内功/02-网络' },
      ],
    },
    {
      type: 'category',
      label: '数据结构',
      items: [
        { type: 'autogenerated', dirName: '02-系统基础内功/03-数据结构' },
      ],
    },
  ],
  // java 侧边栏
  Java相关: [
    {
      type: 'category',
      label: '面试技巧',
      items: [
        { type: 'autogenerated', dirName: '05-Java/01-面试技巧' },
      ],
    },
    {
      type: 'category',
      label: '基础知识',
      items: [
        { type: 'autogenerated', dirName: '05-Java/02-基础知识' },
      ],
    },
    {
      type: 'category',
      label: '集合',
      items: [
        { type: 'autogenerated', dirName: '05-Java/03-集合' },
      ],
    },
    {
      type: 'category',
      label: 'IO相关',
      items: [
        { type: 'autogenerated', dirName: '05-Java/04-IO相关' },
      ],
    },
    {
      type: 'category',
      label: 'JVM',
      items: [
        { type: 'autogenerated', dirName: '05-Java/05-JVM' },
      ],
    },
    {
      type: 'category',
      label: '类加载',
      items: [
        { type: 'autogenerated', dirName: '05-Java/06-类加载' },
      ],
    },
    {
      type: 'category',
      label: '并发多线程',
      items: [
        { type: 'autogenerated', dirName: '05-Java/07-并发多线程' },
      ],
    },
    {
      type: 'category',
      label: 'Spring',
      items: [
        { type: 'autogenerated', dirName: '05-Java/08-Spring' },
      ],
    },
    {
      type: 'category',
      label: 'Mybatis',
      items: [
        { type: 'autogenerated', dirName: '05-Java/09-Mybatis' },
      ],
    },
    {
      type: 'category',
      label: '设计模式',
      items: [
        { type: 'autogenerated', dirName: '05-Java/10-设计模式' },
      ],
    },
    {
      type: 'category',
      label: 'Stream流相关',
      items: [
        { type: 'autogenerated', dirName: '05-Java/16-Stream流相关' },
      ],
    },
  ],
  // 数据库相关 侧边栏
  数据库相关: [
    {
      type: 'category',
      label: 'MySQL',
      items: [
        { type: 'autogenerated', dirName: '11-数据库/01-MySQL' },
      ],
    },
    {
      type: 'category',
      label: 'Redis',
      items: [
        { type: 'autogenerated', dirName: '11-数据库/02-Redis' },
      ],
    },
    {
      type: 'category',
      label: 'Oracle',
      items: [
        { type: 'autogenerated', dirName: '11-数据库/03-Oracle' },
      ],
    },
  ],
  // 框架中间件相关 侧边栏
  框架中间件相关: [
    {
      type: 'category',
      label: 'SpringCloud',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/01-SpringCloud' },
      ],
    },
    {
      type: 'category',
      label: 'Zookeeper',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/02-Zookeeper' },
      ],
    },
    {
      type: 'category',
      label: 'Kafka',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/03-Kafka' },
      ],
    },
    {
      type: 'category',
      label: 'RocketMQ',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/04-RocketMQ' },
      ],
    },
    {
      type: 'category',
      label: 'RabbitMQ',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/05-RabbitMQ' },
      ],
    },
    {
      type: 'category',
      label: 'Elasticsearch',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/06-Elasticsearch' },
      ],
    },
    {
      type: 'category',
      label: 'Dubbo',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/07-Dubbo' },
      ],
    },
    {
      type: 'category',
      label: 'Netty',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/08-Netty' },
      ],
    },
    {
      type: 'category',
      label: 'XXL-JOB',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/09-XXL-JOB' },
      ],
    },
    {
      type: 'category',
      label: 'Tomcat',
      items: [
        { type: 'autogenerated', dirName: '16-框架中间件/10-Tomcat' },
      ],
    },
  ],
  // 架构进阶设计 侧边栏
  架构进阶设计: [
    {
      type: 'category',
      label: '微服务相关',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/01-微服务相关' },
      ],
    },
    {
      type: 'category',
      label: '分布式相关理论',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/02-分布式相关理论' },
      ],
    },
    {
      type: 'category',
      label: '分布式id',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/03-分布式id' },
      ],
    },
    {
      type: 'category',
      label: '限流与熔断',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/04-限流与熔断' },
      ],
    },
    {
      type: 'category',
      label: '缓存的设计',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/05-缓存的设计' },
      ],
    },
    {
      type: 'category',
      label: '布隆过滤器',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/06-布隆过滤器' },
      ],
    },
    {
      type: 'category',
      label: '分布式事务',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/07-分布式事务' },
      ],
    },
    {
      type: 'category',
      label: 'Seata',
      items: [
        { type: 'autogenerated', dirName: '21-架构进阶设计/08-Seata' },
      ],
    },
  ],
  // 架构进阶设计 侧边栏
  问题解决与性能优化: [
    {
      type: 'category',
      label: '问题故障解决',
      items: [
        { type: 'autogenerated', dirName: '26-问题解决与性能优化/01-问题故障解决' },
      ],
    },
    {
      type: 'category',
      label: '分库分表',
      items: [
        { type: 'autogenerated', dirName: '26-问题解决与性能优化/02-分库分表' },
      ],
    },
    {
      type: 'category',
      label: '恶意攻击',
      items: [
        { type: 'autogenerated', dirName: '26-问题解决与性能优化/03-恶意攻击' },
      ],
    },
  ],
};

export default sidebars;
